### ISSUE TITLE
npm install fails for node v14.17.4

### ISSUE THREAD

**Issue by afsalhere** [v8/sampling-heap-profiler#65] opened 2021-08-09 07:24 UTC
make: *** [Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yafsal/Projects/iam/core/node_modules/heap-profile
gyp ERR! node -v v14.17.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by nolanmar511** [comment] 2021-08-09 13:32
This seems like a a duplicate of https://github.com/v8/sampling-heap-profiler/issues/58, since this repo hasn't been updated to be compatible with Node 14.

Trying with the alternative module, https://github.com/google/pprof-nodejs, (as suggested by ofrobots in https://github.com/v8/sampling-heap-profiler/issues/58#issuecomment-771249805) might work.

**Closed by nolanmar511** 2021-08-09 13:32 UTC
